# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :testflight_build do
    match(keychain_name: "login",
      keychain_password: environment_variable(get: "MAC_MINI_SU_PASSWORD"),
      verbose: true)
    increment_build_number(build_number: number_of_commits)
    build_app(workspace: environment_variable(get: "WORKSPACE"), scheme: environment_variable(get: "SCHEME"), clean: true)
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

  desc "Run unit test"
  lane :test do
    scan(workspace: environment_variable(get: "WORKSPACE"),
      scheme: environment_variable(get: "SCHEME"),
      device: "iPhone 8",
      clean: true)
  end
end
